fix lltest example
lltest: added statfs implementation. on macOS, statfs is called frequently.
util: for Darwin (macOS) removed the -l option from umount

subprocess.CalledProcessError: Command '['umount', '-l', '/private/var/folders/61/qtqwzmxd7t1fb19zck5k3q0h0000gn/T/pytest-of-tw/pytest-8/test_lltest0']' returned non-zero exit status 1.
--- Captured stderr call ----------------------------
umount: illegal option -- l
usage: umount [-fv] [-t fstypelist] special | node
       umount -a[fv] [-h host] [-t fstypelist]